#!/usr/bin/env ruby

require 'pry'

def fib(num=0)
  n,y,x = 0,0,1
  while n != num do
    y,x = x,x+y
    n = n+1
  end
  y
end

def fibsum(num=0)
  n,z,y,x = 0,0,1,0
  while n != num do
    z,y,x = z+y,y+x,y
    n = n+1
  end
  z
end

binding.pry