#!/usr/bin/env ruby

require 'pry'

def fib(num=0)
  n,y,x = 0,0,1
  while n != num do
    y,x = x,x+y
    n = n+1
  end
  y
end

def oracle(num=0)
  (0..num).map { |i| fib(i) * fib(num-i) }.sum
end

def fibconv(num=0)
  n,z,y,x,w = 0,0,0,0,1
  while n != num do
    z,y,x,w = z+y+x,z,w,w+x
    n = n+1
  end
  z
end

binding.pry